/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthTruelayerErrorRouteImport } from './routes/auth/truelayer/error'
import { Route as AuthTruelayerCallbackRouteImport } from './routes/auth/truelayer/callback'
import { Route as AuthMonzoErrorRouteImport } from './routes/auth/monzo/error'
import { Route as AuthMonzoCallbackRouteImport } from './routes/auth/monzo/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTruelayerErrorRoute = AuthTruelayerErrorRouteImport.update({
  id: '/auth/truelayer/error',
  path: '/auth/truelayer/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTruelayerCallbackRoute = AuthTruelayerCallbackRouteImport.update({
  id: '/auth/truelayer/callback',
  path: '/auth/truelayer/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMonzoErrorRoute = AuthMonzoErrorRouteImport.update({
  id: '/auth/monzo/error',
  path: '/auth/monzo/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMonzoCallbackRoute = AuthMonzoCallbackRouteImport.update({
  id: '/auth/monzo/callback',
  path: '/auth/monzo/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/monzo/callback': typeof AuthMonzoCallbackRoute
  '/auth/monzo/error': typeof AuthMonzoErrorRoute
  '/auth/truelayer/callback': typeof AuthTruelayerCallbackRoute
  '/auth/truelayer/error': typeof AuthTruelayerErrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/monzo/callback': typeof AuthMonzoCallbackRoute
  '/auth/monzo/error': typeof AuthMonzoErrorRoute
  '/auth/truelayer/callback': typeof AuthTruelayerCallbackRoute
  '/auth/truelayer/error': typeof AuthTruelayerErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/monzo/callback': typeof AuthMonzoCallbackRoute
  '/auth/monzo/error': typeof AuthMonzoErrorRoute
  '/auth/truelayer/callback': typeof AuthTruelayerCallbackRoute
  '/auth/truelayer/error': typeof AuthTruelayerErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/auth/monzo/callback'
    | '/auth/monzo/error'
    | '/auth/truelayer/callback'
    | '/auth/truelayer/error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/monzo/callback'
    | '/auth/monzo/error'
    | '/auth/truelayer/callback'
    | '/auth/truelayer/error'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/auth/monzo/callback'
    | '/auth/monzo/error'
    | '/auth/truelayer/callback'
    | '/auth/truelayer/error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthMonzoCallbackRoute: typeof AuthMonzoCallbackRoute
  AuthMonzoErrorRoute: typeof AuthMonzoErrorRoute
  AuthTruelayerCallbackRoute: typeof AuthTruelayerCallbackRoute
  AuthTruelayerErrorRoute: typeof AuthTruelayerErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/truelayer/error': {
      id: '/auth/truelayer/error'
      path: '/auth/truelayer/error'
      fullPath: '/auth/truelayer/error'
      preLoaderRoute: typeof AuthTruelayerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/truelayer/callback': {
      id: '/auth/truelayer/callback'
      path: '/auth/truelayer/callback'
      fullPath: '/auth/truelayer/callback'
      preLoaderRoute: typeof AuthTruelayerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/monzo/error': {
      id: '/auth/monzo/error'
      path: '/auth/monzo/error'
      fullPath: '/auth/monzo/error'
      preLoaderRoute: typeof AuthMonzoErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/monzo/callback': {
      id: '/auth/monzo/callback'
      path: '/auth/monzo/callback'
      fullPath: '/auth/monzo/callback'
      preLoaderRoute: typeof AuthMonzoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthMonzoCallbackRoute: AuthMonzoCallbackRoute,
  AuthMonzoErrorRoute: AuthMonzoErrorRoute,
  AuthTruelayerCallbackRoute: AuthTruelayerCallbackRoute,
  AuthTruelayerErrorRoute: AuthTruelayerErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
